### ISSUE TITLE
Request: clearer readme for people with less experience

### ISSUE THREAD

**Issue by someone-somewhere-somewhen** [CodeRedModding/CodeRed-Generator#13]
I promise I'm not trying to be a jerk, it's just that I'm just semi-competent at best, and I highly doubt I'm the only one.

I'm just gonna walk through every step listed in the process, even the ones that are fine, in hopes of being as clear as possible.  Sorry that this makes for more text

-

If I understand the very first bit, and I might not, you change the folder name to one matching the game you want to create an SDK for, and then change the paths in Engine.hpp to reflect the changed folder name.  If I understand that correctly, would appear to be fine.  If I'm not understanding correctly my second guess it's the name for some project you want to work on with the SDK, which isn't how an SDK is usually used, but regardless.

The the next bit is simple because it's just (paraphrased) "log or no log", and "only use the UTF16 character set if the game is in UTF16."

The third bit is less clear.  Every configuration option comes with an explanation of what it does (good) but you need to already know why you would want one option over the other (less good) and for someone just starting out some of it is kind of obtuse.  For example, how do I find a game's hex escape value, and how do I know if I want the version printed in the final SDK to be the same or different from the one in the game?

The next part loses me.
> Any class/struct member outside of whats in the EMemberTypes does NOT need to be registered

Ok, but what **is** in EMemberTypes, I _think_ it's listed Framework/Member.hpp lines 32 to 65, but that's not clear, and if it _is_ already contained within the project, why is this a manual step and how do I know which of the EMemeberTypes I should add/remove?

Next step is double checking things and making sure the output path is set and such, which is perfectly clear.

> After that just compile as a DLL and manually inject into your game

I'm sure I can google this, so it's a minor point, but a) I've literally never made a dll, so if the process is different from compiling other code I'm not sure how, and b) I've never manually injected a DLL either.  Though (again) I'm sure I can google it if/when the time actually comes.

**Comment by ItsBranK** [comment]
There are examples of al the member types and where they would be in the template example files. This is not a tool you can just inject and it works, you need to reverse the game you want to use this with first. If you don't know how sdk generation works or even how to compile a dll, this is not the project for you. It's not for script kiddies with no knowledge of unreal engine who just want to magically cheat in games.
