### ISSUE TITLE
Can we have an example game for the config "engine"?

### ISSUE THREAD

**Issue by Tom-Neverwinter** [CodeRedModding/CodeRed-Generator#6]
Hawken was a good example. [the pax version is floating around somewhere] https://drive.google.com/file/d/1bXj0wxjNct_kvndWWufxPqKWVnHdP2zV/view?usp=sharing

looking at the format of the other ones like apb and alone in the dark etc.

**Comment by HOOSIER0x007** [comment]
> Hawken was a good example. [the pax version is floating around somewhere] https://drive.google.com/file/d/1bXj0wxjNct_kvndWWufxPqKWVnHdP2zV/view?usp=sharing
> 
> looking at the format of the other ones like apb and alone in the dark etc.

Looks like he dont care bud. Posts a project that clearly does not work  and then wont even reply. 
I forked his code and the signature scanning is not working correclty. 
I aksed him for an example of his sigs and masks. 
Bypassing them also produced a busted log. 
So if he does not reply im going to fix this dumpster fire and inlcude actual information he left out. 
There are very few ue3 x64 games out there. 
My own customized freckless gen works just fine it can create a base PE or 
Function hook etc. I have tried every patter style known to c++ they all come back bad or wrong. 
So something is fully wrong with how he scans.

**Comment by ItsBranK** [comment]
I won't put any third party game sources here to reduce the risk of this being taken down via a copyright strike, you can follow feckless's tutorial on how to reverse game structs. The generator works fine, I use it myself for Rocket League and also a slightly modified version for Mortal Kombat 11.
